Use the default gradle configuration for the java canary
We add no dependencies to the archives configuration, causing
NoClassDefFoundErrors in the canary at runtime.